source "https://rubygems.org"

gem "sinatra", "~> 4.0"
gem "puma", "~> 6.0"
gem "rack-contrib", "~> 2.4"
gem "rackup", "~> 2.1"

gem "sequel", "~> 5.0"
gem "pg", "~> 1.5"

gem "redis", "~> 5.0"

gem "jwt", "~> 2.8"
