server:
  port: ${PORT:8080}
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  pattern:
    console: '{"time":"%d{ISO8601}","level":"%p","logger":"%logger","message":"%m"}%n'
